language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

install:
    - composer self-update
    - composer install --dev --prefer-dist

script:
    - phpunit --bootstrap vendor/autoload.php tests
    - vendor/bin/behat
